### ISSUE TITLE
Wallet Won't Open

### ISSUE THREAD

**Issue by BigBoy67grad** [hexxcointakeover/hexxcoin#17]
Opening the wallet yesterday resulted in the wallet hanging when attempting to synchronize. The wallet ended up being closed during the hang. When trying to open it today the debug file for the wallet lists the following problems:

2018-06-17 23:20:16 GUI: "registerShutdownBlockReason: Successfully registered: Hexxcoin Core didn't yet exit safely..."

And later:

2018-06-17 23:20:24 ERROR: ConnectTip(): ConnectBlock e12ccdc723bee929a1d2e57ed921cc48546c22d2550b7d9357c2652e145ee4b5 failed

Is there a way to rectify the issue and open the wallet?

**Comment by svhill11** [comment]
The wallet will not open. This version simply says "Loading block index..." and goes on and on and never opens. This is very frustrating because my old wallet opened and yet would not update after a while. Why is it you cannot simply create ONE WALLET which updates? As it is I have NO WAY to get to my Hexx coins. They are stuck on the old wallet and no matter which laptop or PC I use the new wallet will not open or load the block index (and I have the old wallet closed). Not only that, this new wallet triggers all anti virus protections whereas you old one did not. None of my other wallets do that. Please get your act together. I cannot wait until you fork with BTC so I can simply dump this on Nano Ledger S. Please advise what to do.

**Comment by devcon-gh** [comment]
Just update to the latest wallet ( [4.0.3.8](https://github.com/hexxcointakeover/hexxcoin/releases/tag/4.0.3.8) )? 

If wallet won't sync reinstall the chainfiles:

```
Close/Quit local wallet. 
Navigate to your hexxcoin/application folder.
 (Windows) -> C:\Users\Username\AppData\Roaming\hexxcoin
(Mac) -> /Users/Username/Library/Application Support/hexxcoin
(Unix) -> /.hexxcoin
Remove/delete every folder and files EXCEPT wallet.dat (and xnode.conf if you have an Xnode).
Download the latest chainfiles -> https://github.com/hexxcointakeover/hexxcoin/releases/download/chain/chainfiles.zip
Extract/unzip the chainfiles zip in the hexxcoin/application folder
 Restart your wallet
```

If wallet still isn’t syncing after a while, you probably don’t have enough connections, add some nodes manually to increase connections.

```
Go to https://chainz.cryptoid.info/hxx/#!network and click on  node list (/Hexx:4.0.3.8/)
Add those ip’s to your console (line for line): help -> debug -> console 
Command is: addnode IP:29100 add
Example -> addnode 81.171.19.244:29100 add
```

**Comment by svhill11** [comment]
The wallet will not open. It is not a matter of syncing because the old wallet synced and worked fine. You have a glitch in this software that causes it to either not open or if it does finally open it hangs at 48 weeks for a day or two. That is a coding glitch. Fix the code please. It is not an issue with the nodes.

**Comment by devcon-gh** [comment]
Did you even try what i suggest? There is no glitch or coding issue. For example the Exchanges and Xnodes use same wallet without problems.

**Comment by svhill11** [comment]
Yes I did exactly what you said. The last version of the wallet had no issues on my computers. This version is sticking at 48 weeks. If I leave the old wallet files in new files will not open...it simply says loading files and will not open.



I am not going in an adding nodes. Why should I do that? I am not a programmer. Provide me with a wallet that works please.

**Comment by svhill11** [comment]
I do not have this issue with any other wallet I have but every update I get from Hexx there is some issue.

**Comment by svhill11** [comment]
I notice there is someone else above that has the same issue with the wallet hanging so I am not alone.

**Comment by revizionary1** [comment]
I had the same issue as svhill11 and I simply did a fresh install and backed up my wallet.dat file like he said above and it worked (on a USB). For some reason when I left it on my hard drive I still had an issue loading. But once I deleted any old files and made sure I kept the wallet.dat it worked OK and eventually started updating on the new wallet.

**Comment by devcon-gh** [comment]
I'm glad the issues been solved.
